version: "3"
services:
  app:
    build: .
    volumes:
      - .:/opt/app
    ports:
      - "5000:5000"
    # tty: true
    environment:
      - port=6000
    command: flask run -h 0.0.0.0 --cert ssl/server.crt --key ssl/server.key
