"""initial file

Revision ID: f99a415f3b8a
Revises: 
Create Date: 2021-01-19 17:29:27.380518

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "f99a415f3b8a"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("subid", sa.String(length=50), nullable=True),
        sa.Column("name", sa.String(length=50), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
        sa.UniqueConstraint("subid"),
    )
    op.create_table(
        "website",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("name", sa.String(length=50), nullable=False),
        sa.Column("siteurl", sa.String(length=50), nullable=True),
        sa.Column("feedurl", sa.String(length=50), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("website")
    op.drop_table("user")
    # ### end Alembic commands ###
